import { describe, expect, it } from 'vitest'
import { PDFDocument } from 'pdf-lib'
import { renderPdfDocument, renderSimplePdf } from './simple-pdf'

describe('renderSimplePdf', () => {
  it('creates a valid PDF buffer from markdown-like content', async () => {
    const buffer = await renderSimplePdf({
      title: 'Sample PDF',
      content: '# Heading\n\n- First item\n- Second item\n\nThis is a generated document.',
    })

    const loaded = await PDFDocument.load(buffer)
    expect(buffer.byteLength).toBeGreaterThan(500)
    expect(loaded.getPageCount()).toBeGreaterThan(0)
  })

  it('creates a valid PDF from structured document fields and tables', async () => {
    const buffer = await renderPdfDocument({
      title: 'Structured PDF',
      template: 'report',
      subtitle: 'A richer document contract',
      sections: [
        {
          heading: 'Overview',
          body: 'This document is rendered from structured sections.',
          bullets: ['Reusable template', 'Canvas artifact download'],
        },
      ],
      fields: [{ label: 'Status', value: 'Ready' }],
      tables: [{
        title: 'Budget',
        columns: ['Item', 'Amount'],
        rows: [{ Item: 'Hosting', Amount: '$299' }],
      }],
      metadata: { footer: 'Generated by PeakUI' },
    })

    const loaded = await PDFDocument.load(buffer)
    expect(buffer.byteLength).toBeGreaterThan(500)
    expect(loaded.getPageCount()).toBeGreaterThan(0)
  })
})
