import { describe, expect, it } from 'vitest'
import { PDFDocument } from 'pdf-lib'
import { renderPdfDocument, renderSimplePdf } from './simple-pdf'

describe('renderSimplePdf', () => {
  it('creates a valid PDF buffer from markdown-like content', async () => {
    const buffer = await renderSimplePdf({
      title: 'Sample PDF',
      content: '# Heading\n\n- First item\n- Second item\n\nThis is a generated document.',
    })

    const loaded = await PDFDocument.load(buffer)
    expect(buffer.byteLength).toBeGreaterThan(500)
    expect(loaded.getPageCount()).toBeGreaterThan(0)
  })

  it('creates a valid PDF from structured document fields and tables', async () => {
    const buffer = await renderPdfDocument({
      title: 'Structured PDF',
      template: 'report',
      subtitle: 'A richer document contract',
      sections: [
        {
          heading: 'Overview',
          body: 'This document is rendered from structured sections.',
          bullets: ['Reusable template', 'Canvas artifact download'],
        },
      ],
      fields: [{ label: 'Status', value: 'Ready' }],
      tables: [{
        title: 'Budget',
        columns: ['Item', 'Amount'],
        rows: [{ Item: 'Hosting', Amount: '$299' }],
      }],
      metadata: { footer: 'Generated by PeakUI' },
    })

    const loaded = await PDFDocument.load(buffer)
    expect(buffer.byteLength).toBeGreaterThan(500)
    expect(loaded.getPageCount()).toBeGreaterThan(0)
  })

  it('creates a valid PDF from a title-only request (no structured content)', async () => {
    const buffer = await renderPdfDocument({
      title: 'Meeting Notes',
      description: 'Notes from the kickoff meeting.',
    })

    const loaded = await PDFDocument.load(buffer)
    expect(buffer.byteLength).toBeGreaterThan(500)
    expect(loaded.getPageCount()).toBeGreaterThan(0)
  })

  it('renders a themed PDF across templates with callouts and zebra tables', async () => {
    const buffer = await renderPdfDocument({
      title: 'Invoice',
      template: 'invoice',
      subtitle: 'March 2026',
      fields: [{ label: 'Invoice #', value: 'INV-1042' }],
      sections: [{
        heading: 'Line Items',
        tables: [{
          title: 'Services',
          columns: ['Service', 'Amount'],
          rows: [{ Service: 'Consulting', Amount: '$1,200' }, { Service: 'Hosting', Amount: '$300' }],
        }],
        callouts: [{ tone: 'success', title: 'Paid', text: 'Thank you for your business.' }],
      }],
    })

    const loaded = await PDFDocument.load(buffer)
    expect(buffer.byteLength).toBeGreaterThan(500)
    expect(loaded.getPageCount()).toBeGreaterThan(0)
  })
})
