import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

const PAGE_WIDTH = 612
const PAGE_HEIGHT = 792
const MARGIN = 54
const TITLE_SIZE = 18
const BODY_SIZE = 11
const LINE_HEIGHT = 15

function wrapLine(line: string, maxChars: number): string[] {
  const words = line.replace(/\s+/g, ' ').trim().split(' ').filter(Boolean)
  if (words.length === 0) return ['']
  const wrapped: string[] = []
  let current = ''
  for (const word of words) {
    const candidate = current ? `${current} ${word}` : word
    if (candidate.length > maxChars && current) {
      wrapped.push(current)
      current = word
    } else {
      current = candidate
    }
  }
  if (current) wrapped.push(current)
  return wrapped
}

export async function renderSimplePdf(input: {
  title: string
  content: string
  footer?: string
}): Promise<Buffer> {
  const pdf = await PDFDocument.create()
  const regular = await pdf.embedFont(StandardFonts.Helvetica)
  const bold = await pdf.embedFont(StandardFonts.HelveticaBold)
  const maxChars = 88
  let page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT])
  let y = PAGE_HEIGHT - MARGIN
  let pageNumber = 1

  const drawFooter = () => {
    page.drawText(input.footer || `Generated by PeakUI · Page ${pageNumber}`, {
      x: MARGIN,
      y: 28,
      size: 8,
      font: regular,
      color: rgb(0.35, 0.38, 0.45),
    })
  }

  const newPage = () => {
    drawFooter()
    page = pdf.addPage([PAGE_WIDTH, PAGE_HEIGHT])
    pageNumber += 1
    y = PAGE_HEIGHT - MARGIN
  }

  const drawTextLine = (text: string, options: { bold?: boolean; size?: number; indent?: number } = {}) => {
    const size = options.size || BODY_SIZE
    if (y < MARGIN + LINE_HEIGHT) newPage()
    page.drawText(text, {
      x: MARGIN + (options.indent || 0),
      y,
      size,
      font: options.bold ? bold : regular,
      color: rgb(0.07, 0.09, 0.15),
      maxWidth: PAGE_WIDTH - MARGIN * 2 - (options.indent || 0),
    })
    y -= size === TITLE_SIZE ? 24 : LINE_HEIGHT
  }

  drawTextLine(input.title || 'Generated PDF', { bold: true, size: TITLE_SIZE })
  y -= 6

  const lines = input.content
    .replace(/\r\n/g, '\n')
    .split('\n')
    .flatMap(rawLine => {
      const trimmed = rawLine.trimEnd()
      if (!trimmed.trim()) return ['']
      return wrapLine(trimmed, maxChars)
    })

  for (const line of lines) {
    if (!line.trim()) {
      y -= LINE_HEIGHT
      continue
    }
    const heading = /^(#{1,3})\s+(.+)$/.exec(line)
    if (heading) {
      y -= 4
      drawTextLine(heading[2], { bold: true, size: heading[1].length === 1 ? 15 : 13 })
      continue
    }
    const bullet = /^[-*]\s+(.+)$/.exec(line)
    if (bullet) {
      drawTextLine(`• ${bullet[1]}`, { indent: 10 })
      continue
    }
    drawTextLine(line)
  }

  drawFooter()
  return Buffer.from(await pdf.save())
}
