import { describe, expect, it } from 'vitest'
import { normalizeWordDocumentInput } from './word-schema'
import { renderWordDocument } from './word-renderer'

describe('renderWordDocument', () => {
  it('creates a valid DOCX buffer from structured document content', async () => {
    const normalized = normalizeWordDocumentInput({
      title: 'Services Proposal',
      template: 'proposal',
      subtitle: 'Prepared by PeakUI',
      fields: [{ label: 'Client', value: 'Acme Corp' }],
      sections: [
        {
          heading: 'Executive Summary',
          body: 'This proposal is rendered from structured Word document content.',
          bullets: ['Discovery', 'Implementation', 'Handoff'],
        },
        {
          heading: 'Pricing',
          tables: [{
            title: 'Fees',
            columns: ['Item', 'Amount'],
            rows: [{ Item: 'Implementation', Amount: '$4,500' }],
          }],
          callouts: [{ tone: 'note', title: 'Next Step', text: 'Review and approve the proposal.' }],
        },
      ],
      metadata: { author: 'PeakUI', footer: 'Generated by PeakUI' },
    })

    const buffer = await renderWordDocument(normalized)
    expect(buffer.byteLength).toBeGreaterThan(1000)
    expect(buffer.subarray(0, 2).toString('utf8')).toBe('PK')
  })
})
