import { NextRequest, NextResponse } from 'next/server'
import { prisma } from '@/lib/prisma'
import { requireCurrentAuthWithPermissions } from '@/lib/request-auth'
import { createPdfCanvasArtifact } from '@/lib/pdf/pdf-artifacts'
import { renderSimplePdf } from '@/lib/pdf/simple-pdf'

export const runtime = 'nodejs'
export const maxDuration = 60

function sanitizeFilename(value: string): string {
  const clean = value.trim().split(/[\\/]/).pop()?.replace(/[^a-zA-Z0-9._-]+/g, '-') || 'generated-document'
  return clean.toLowerCase().endsWith('.pdf') ? clean : `${clean}.pdf`
}

export async function POST(request: NextRequest) {
  const access = await requireCurrentAuthWithPermissions(['openclaw.use', 'canvas.use'], {
    forbiddenMessage: 'PDF generation requires WorkSpaces and Canvas permissions.',
  })
  if ('response' in access) return access.response

  try {
    const body = await request.json().catch(() => ({}))
    const title = typeof body?.title === 'string' && body.title.trim() ? body.title.trim() : 'Generated PDF'
    const content = typeof body?.content === 'string' ? body.content.trim() : ''
    const sessionId = typeof body?.sessionId === 'string' && body.sessionId.trim() ? body.sessionId.trim() : ''
    const messageId = typeof body?.messageId === 'string' && body.messageId.trim() ? body.messageId.trim() : null
    const filename = sanitizeFilename(typeof body?.filename === 'string' && body.filename.trim() ? body.filename.trim() : title)

    if (!sessionId) {
      return NextResponse.json({ error: 'sessionId is required' }, { status: 400 })
    }
    if (!content) {
      return NextResponse.json({ error: 'content is required' }, { status: 400 })
    }
    if (content.length > 60_000) {
      return NextResponse.json({ error: 'PDF content is too large for a single generated document' }, { status: 413 })
    }

    const pdfBytes = await renderSimplePdf({
      title,
      content,
      footer: 'Generated by PeakUI',
    })

    const artifact = await prisma.$transaction(tx => createPdfCanvasArtifact({
      tx,
      userId: access.userId,
      sessionId,
      messageId,
      name: filename,
      pdfBytes,
      bundleName: title,
      bundleRole: 'generated-pdf',
    }))

    return NextResponse.json({
      success: true,
      artifact: {
        id: artifact.id,
        name: artifact.name,
        mimeType: artifact.mimeType,
        size: artifact.size,
        downloadUrl: `/api/canvas/artifacts/${artifact.id}/download`,
      },
    })
  } catch (error) {
    console.error('[openclaw/pdf-document] POST error:', error)
    return NextResponse.json({
      error: error instanceof Error ? error.message : 'PDF generation failed',
    }, { status: 500 })
  }
}
