#!/usr/bin/env sh
# PeakUI one-command installer — Linux / macOS.
#
#   curl -fsSL https://raw.githubusercontent.com/rajatalha150/PeakUI/main/scripts/install.sh | sh
#
# Or, after a manual clone, from the repo root:
#   ./scripts/install.sh [target_dir]
#
# Idempotent: safe to re-run to update an existing deployment.
# The only hard prerequisite is Docker (+ the `docker compose` plugin).
# Ollama is a soft prerequisite — the stack comes up without it.

set -eu

REPO="https://github.com/rajatalha150/PeakUI.git"
BRANCH="main"
PORT="${PEAKUI_PORT:-3000}"

# Target dir: explicit arg > env > ./PeakUI in the current working directory.
# (When piped from curl, $PWD is wherever the user ran the command.)
TARGET="${1:-${PEAKUI_TARGET:-$PWD/PeakUI}}"

if [ -t 1 ]; then
  C_BLUE='\033[1;34m'; C_GREEN='\033[1;32m'; C_YELLOW='\033[1;33m'; C_RED='\033[1;31m'; C_OFF='\033[0m'
else
  C_BLUE=''; C_GREEN=''; C_YELLOW=''; C_RED=''; C_OFF=''
fi
log()  { printf "${C_BLUE}==>${C_OFF} %s\n" "$*"; }
ok()   { printf "${C_GREEN}==>${C_OFF} %s\n" "$*"; }
warn() { printf "${C_YELLOW}==>${C_OFF} %s\n" "$*" >&2; }
die()  { printf "${C_RED}==>${C_OFF} %s\n" "$*" >&2; exit 1; }

# --- 1. Detect OS / pick compose file ---------------------------------------
OS="$(uname -s 2>/dev/null || echo unknown)"
case "$OS" in
  Linux*)  COMPOSE_FILE="docker-compose.yml";           DB_HOST="localhost";            OLLAMA_HOST="http://127.0.0.1:11434"; TOR_URL="socks5://localhost:9050" ;;
  Darwin*) COMPOSE_FILE="docker-compose.windows.yml";    DB_HOST="db";                   OLLAMA_HOST="http://host.docker.internal:11434"; TOR_URL="socks5://tor-proxy:9150" ;;
  *) die "Unsupported OS '$OS'. Use Windows PowerShell: irm https://raw.githubusercontent.com/rajatalha150/PeakUI/main/scripts/install.ps1 | iex" ;;
esac

# --- 2. Verify Docker -------------------------------------------------------
command -v docker >/dev/null 2>&1 || die "Docker is not installed. Install it first: https://docs.docker.com/get-docker/"
log "Checking Docker daemon..."
docker info >/dev/null 2>&1 || die "Docker daemon is not running. Start Docker and re-run this command."
docker compose version >/dev/null 2>&1 || die "The 'docker compose' plugin is missing. Install the Docker Compose plugin (v2) and re-run."
ok "Docker is available."

# --- 3. Obtain / update the repository --------------------------------------
if [ -f "$TARGET/docker-compose.yml" ]; then
  log "Updating existing checkout at $TARGET"
  cd "$TARGET"
  git rev-parse --is-inside-work-tree >/dev/null 2>&1 || die "$TARGET is not a git checkout; move it aside and re-run."
  git fetch --quiet origin "$BRANCH" 2>/dev/null || warn "git fetch failed (offline?) — continuing with current checkout."
  git checkout "$BRANCH" 2>/dev/null || true
  git pull --ff-only --quiet origin "$BRANCH" 2>/dev/null || warn "git pull failed — continuing with current checkout."
else
  log "Cloning PeakUI into $TARGET"
  mkdir -p "$(dirname "$TARGET")"
  git clone --depth 1 --branch "$BRANCH" "$REPO" "$TARGET"
  cd "$TARGET"
fi
[ -f "$COMPOSE_FILE" ] || die "$COMPOSE_FILE not found in $TARGET — incomplete checkout."

# --- 4. Generate .env (idempotent) ------------------------------------------
if [ -f .env ]; then
  ok ".env already exists — keeping your values."
else
  log "Generating .env with random secrets..."
  # base64 of /dev/urandom; strip shell/URL-unsafe chars.
  rand() { head -c "$1" /dev/urandom 2>/dev/null | base64 | tr -d '/+=\n' | cut -c1-"$2"; }
  PG_PASS="$(rand 24 24)"; [ -n "$PG_PASS" ] || PG_PASS="peakui_$(date 2>/dev/null || echo changeme)"
  JWT_SECRET="$(rand 48 64)"; [ -n "$JWT_SECRET" ] || JWT_SECRET="peakui_jwt_$(date 2>/dev/null || echo changeme)"
  HOME_DIR="${OPENCLAW_HOST_HOME_DIR:-$HOME}"
  TMP_DIR="${OPENCLAW_HOST_TMP_DIR:-/tmp}"
  WORKSPACE_DIR="${OPENCLAW_HOST_WORKSPACE_DIR:-$HOME/.peakui/workspace}"
  PROJECTS_DIR="${OPENCLAW_HOST_PROJECTS_DIR:-$HOME/Desktop}"
  mkdir -p "$WORKSPACE_DIR" "$PROJECTS_DIR" 2>/dev/null || true
  cat > .env <<EOF
# PeakUI environment — generated by scripts/install.sh
# This file is gitignored. Do not commit it.

POSTGRES_USER=peakui
POSTGRES_PASSWORD=$PG_PASS
POSTGRES_DB=peakui
DATABASE_URL=postgresql://peakui:$PG_PASS@$DB_HOST:5432/peakui
JWT_SECRET=$JWT_SECRET
OLLAMA_HOST=$OLLAMA_HOST
OPENCLAW_HOST_HOME_DIR=$HOME_DIR
OPENCLAW_HOST_TMP_DIR=$TMP_DIR
OPENCLAW_HOST_WORKSPACE_DIR=$WORKSPACE_DIR
OPENCLAW_HOST_PROJECTS_DIR=$PROJECTS_DIR
TOR_PROXY_URL=$TOR_URL
EOF
  chmod 600 .env
  ok ".env created."
fi

# --- 5. Build + start (detached) -------------------------------------------
log "Building and starting PeakUI (first build takes a few minutes)..."
docker compose -f "$COMPOSE_FILE" up -d --build

# --- 6. Wait for the app and report ----------------------------------------
log "Waiting for the app to come up on http://localhost:$PORT ..."
i=0
while [ "$i" -lt 90 ]; do
  if curl -fsS -o /dev/null "http://localhost:$PORT/" 2>/dev/null; then
    printf "\n${C_GREEN}PeakUI is running at http://localhost:$PORT${C_OFF}\n"
    printf "  • On first visit, create the initial admin account.\n"
    printf "  • Ollama: set OLLAMA_HOST in Settings if it's not at %s\n" "$OLLAMA_HOST"
    printf "  • Logs:   docker compose -f %s logs -f app\n" "$COMPOSE_FILE"
    printf "  • Stop:   docker compose -f %s down\n" "$COMPOSE_FILE"
    printf "  • Update: re-run this installer (it git-pulls and rebuilds).\n"
    exit 0
  fi
  i=$((i + 1)); sleep 2
done
warn "App did not respond on :$PORT within ~3 minutes."
die "Check logs: docker compose -f $COMPOSE_FILE logs app"